title: Prithvi Kohli
logo: mecropped.jfif
description: 2nd-year CS undergrad at UCL, interested in Computer Graphics. Research Intern in [VECG](http://vecg.cs.ucl.ac.uk/). [prithvikohligames@gmail.com]
theme: jekyll-theme-minimal
