title: Prithvi Kohli
logo: mecropped.jfif
description: 2nd-year CS undergrad at UCL. Research Intern in VECG. Graphics Research Software Engineer at Arm. [prithvikohligames@gmail.com]
theme: jekyll-theme-minimal
